// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyMinderWebAPI.DataAccessLayer.Context;

#nullable disable

namespace MoneyMinderWebAPI.Migrations
{
    [DbContext(typeof(MoneyMinderDataContext))]
    [Migration("20240122230002_AddingAutomaticPaymentLog")]
    partial class AddingAutomaticPaymentLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoneyMinderWebAPI.DomainLayer.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int?>("FkAccountTypeId")
                        .HasColumnType("int")
                        .HasColumnName("FK_AccountTypeID");

                    b.Property<bool>("HouseSavingsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Account__3214EC27BA9D8EFB");

                    b.HasIndex("FkAccountTypeId");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("MoneyMinderWebAPI.DomainLayer.Models.AccountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__AccountT__3214EC27522B8DBA");

                    b.ToTable("AccountType", (string)null);
                });

            modelBuilder.Entity("MoneyMinderWebAPI.DomainLayer.Models.AutomaticPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("FkAccountId")
                        .HasColumnType("int")
                        .HasColumnName("FK_AccountID");

                    b.Property<int?>("FkCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("FK_CategoryID");

                    b.Property<int?>("FkFrequencyId")
                        .HasColumnType("int")
                        .HasColumnName("FK_FrequencyID");

                    b.Property<DateTime?>("LastPaymentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Automati__3214EC278300C151");

                    b.HasIndex("FkAccountId");

                    b.HasIndex("FkCategoryId");

                    b.HasIndex("FkFrequencyId");

                    b.ToTable("AutomaticPayment", (string)null);
                });

            modelBuilder.Entity("MoneyMinderWebAPI.DomainLayer.Models.AutomaticPaymentLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FKAutomaticPaymentId")
                        .HasColumnType("int")
                        .HasColumnName("FK_AutomaticPaymentID");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__AutomaticPaymentLog");

                    b.HasIndex("FKAutomaticPaymentId");

                    b.ToTable("AutomaticPaymentLog", (string)null);
                });

            modelBuilder.Entity("MoneyMinderWebAPI.DomainLayer.Models.HouseSaving", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int?>("FkAccountId")
                        .HasColumnType("int")
                        .HasColumnName("FK_AccountID");

                    b.Property<decimal?>("GoalAmount")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<DateTime?>("GoalDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__HouseSav__3214EC273F4DCF4A");

                    b.HasIndex("FkAccountId");

                    b.ToTable("HouseSaving", (string)null);
                });

            modelBuilder.Entity("MoneyMinderWebAPI.DomainLayer.Models.PaymentFrequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__PaymentF__3214EC279C0A526C");

                    b.ToTable("PaymentFrequency", (string)null);
                });

            modelBuilder.Entity("MoneyMinderWebAPI.DomainLayer.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FkAccountId")
                        .HasColumnType("int")
                        .HasColumnName("FK_AccountID");

                    b.Property<int?>("FkTransactionCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("FK_TransactionCategoryID");

                    b.Property<int?>("FkTransactionTypeId")
                        .HasColumnType("int")
                        .HasColumnName("FK_TransactionTypeID");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__Transact__3214EC278CDE2116");

                    b.HasIndex("FkAccountId");

                    b.HasIndex("FkTransactionCategoryId");

                    b.HasIndex("FkTransactionTypeId");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("MoneyMinderWebAPI.DomainLayer.Models.TransactionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Transact__3214EC274C7960D3");

                    b.ToTable("TransactionCategory", (string)null);
                });

            modelBuilder.Entity("MoneyMinderWebAPI.DomainLayer.Models.TransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Transact__3214EC272AEE813A");

                    b.ToTable("TransactionType", (string)null);
                });

            modelBuilder.Entity("MoneyMinderWebAPI.DomainLayer.Models.Account", b =>
                {
                    b.HasOne("MoneyMinderWebAPI.DomainLayer.Models.AccountType", "FkAccountType")
                        .WithMany("Accounts")
                        .HasForeignKey("FkAccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Account_AccountTypeID");

                    b.Navigation("FkAccountType");
                });

            modelBuilder.Entity("MoneyMinderWebAPI.DomainLayer.Models.AutomaticPayment", b =>
                {
                    b.HasOne("MoneyMinderWebAPI.DomainLayer.Models.Account", "FkAccount")
                        .WithMany("AutomaticPayments")
                        .HasForeignKey("FkAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Automatic_Payment_AccountID");

                    b.HasOne("MoneyMinderWebAPI.DomainLayer.Models.TransactionCategory", "FkCategory")
                        .WithMany("AutomaticPayments")
                        .HasForeignKey("FkCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Automatic_Payment_CategoryID");

                    b.HasOne("MoneyMinderWebAPI.DomainLayer.Models.PaymentFrequency", "FkFrequency")
                        .WithMany("AutomaticPayments")
                        .HasForeignKey("FkFrequencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Automatic_Payment_FrequencyID");

                    b.Navigation("FkAccount");

                    b.Navigation("FkCategory");

                    b.Navigation("FkFrequency");
                });

            modelBuilder.Entity("MoneyMinderWebAPI.DomainLayer.Models.AutomaticPaymentLog", b =>
                {
                    b.HasOne("MoneyMinderWebAPI.DomainLayer.Models.AutomaticPayment", "FKAutomaticPayment")
                        .WithMany("AutomaticPaymentLogs")
                        .HasForeignKey("FKAutomaticPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_AutomaticPaymentLog_Payment");

                    b.Navigation("FKAutomaticPayment");
                });

            modelBuilder.Entity("MoneyMinderWebAPI.DomainLayer.Models.HouseSaving", b =>
                {
                    b.HasOne("MoneyMinderWebAPI.DomainLayer.Models.Account", "FkAccount")
                        .WithMany("HouseSavings")
                        .HasForeignKey("FkAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_HouseSaving_AccountID");

                    b.Navigation("FkAccount");
                });

            modelBuilder.Entity("MoneyMinderWebAPI.DomainLayer.Models.Transaction", b =>
                {
                    b.HasOne("MoneyMinderWebAPI.DomainLayer.Models.Account", "FkAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("FkAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Transaction_Account");

                    b.HasOne("MoneyMinderWebAPI.DomainLayer.Models.TransactionCategory", "FkTransactionCategory")
                        .WithMany("Transactions")
                        .HasForeignKey("FkTransactionCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Transaction_TransactionCategory");

                    b.HasOne("MoneyMinderWebAPI.DomainLayer.Models.TransactionType", "FkTransactionType")
                        .WithMany("Transactions")
                        .HasForeignKey("FkTransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Transaction_TransactionType");

                    b.Navigation("FkAccount");

                    b.Navigation("FkTransactionCategory");

                    b.Navigation("FkTransactionType");
                });

            modelBuilder.Entity("MoneyMinderWebAPI.DomainLayer.Models.Account", b =>
                {
                    b.Navigation("AutomaticPayments");

                    b.Navigation("HouseSavings");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MoneyMinderWebAPI.DomainLayer.Models.AccountType", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("MoneyMinderWebAPI.DomainLayer.Models.AutomaticPayment", b =>
                {
                    b.Navigation("AutomaticPaymentLogs");
                });

            modelBuilder.Entity("MoneyMinderWebAPI.DomainLayer.Models.PaymentFrequency", b =>
                {
                    b.Navigation("AutomaticPayments");
                });

            modelBuilder.Entity("MoneyMinderWebAPI.DomainLayer.Models.TransactionCategory", b =>
                {
                    b.Navigation("AutomaticPayments");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MoneyMinderWebAPI.DomainLayer.Models.TransactionType", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
